"""Adding columns to connections table

Revision ID: 7e5f85cb06e5
Revises: 4082e63d6c98
Create Date: 2025-08-05 04:38:36.405271

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7e5f85cb06e5'
down_revision: Union[str, Sequence[str], None] = '4082e63d6c98'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('delete_me')
    op.add_column('connections', sa.Column('connection_type', sa.String(), nullable=False))
    op.add_column('connections', sa.Column('is_active', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('connections', 'is_active')
    op.drop_column('connections', 'connection_type')
    op.create_table('delete_me',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('delete_me_pkey'))
    )
    # ### end Alembic commands ###
